ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS planned_hours numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS hourly_rate numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_budget numeric NOT NULL DEFAULT 0;